### ISSUE TITLE
MySQL Timeout (Reminder for 2.0.8 dev work)

### ISSUE THREAD

**Issue by KeepJ96** [KeepJ96/IP-Check#13]
# Bug report template 

**IP-Check Version**: 2.0.7 b2084

**Java Version**: N/A

**Database Type**: MySQL

**Description of the problem**: Need to add ?autoReconnect=true to connection string.

**How to replicate**: Launch IPC and wait several hours, then perform any command.

**Checklist**:

- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/KeepJ96/IP-Check/issues)
- [x] I made sure I am using an up-to-date version of IP-Check.
- [x] I Made sure the bug/error is not caused by any other plugin.

**Comment by dutchy1001** [comment]
an error report when the connection is broken after serveral hours
http://pastebin.com/ecX5Rxkw

**Comment by KeepJ96** [comment]
Just to make it easier to know what the error is (instead of searching through that massive error log):

`[10:38:29] [Server thread/WARN]: Caused by: java.io.EOFException: Can not read response from server.`
`Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.`
`[10:38:29] [Server thread/WARN]:   at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3008)`
`[10:38:29] [Server thread/WARN]:   at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3466)`
`[10:38:29] [Server thread/WARN]:   ... 32 more`
`[10:38:29] [Server thread/ERROR]: [IP-Check] An error occurred while attempting to generate a prepared statement for the database.`
`[10:38:29] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.`

**Comment by dutchy1001** [comment]
lol
