### ISSUE TITLE
Error on whitelist server

### ISSUE THREAD

**Issue by mechcalvin** [KeepJ96/IP-Check#18]
# Issue Report 

**IP-Check Version:**
2.07

**Java Version:**
8

**Database Type:**
file

**Description of the problem:**
when a player that is not whitelisted this error will spam the console.
ERROR Could not pass event PlayerLoginEvent to IP-Check v2.0.7

**How to replicate**:

---
setup whitelist server, ask a non-whitelisted player to login, this error will show

**Checklist**:

- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/KeepJ96/IP-Check/issues)
- [x] I made sure I am using an up-to-date version of IP-Check.
- [x] I Made sure the bug/error is not caused by any other plugin.

**Comment by dutchy1001** [comment]
Could you post the error as this is critical to see to solve the isssue

**Comment by mechcalvin** [comment]
[17:51:48] [Server thread/ERROR]: Could not pass event PlayerLoginEvent to IP-Check v2.0.7
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:git-Spigot-4741400-a1d3777]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-4741400-a1d3777]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot.jar:git-Spigot-4741400-a1d3777]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot.jar:git-Spigot-4741400-a1d3777]
	at net.minecraft.server.v1_11_R1.PlayerList.attemptLogin(PlayerList.java:501) [Spigot.jar:git-Spigot-4741400-a1d3777]
	at net.minecraft.server.v1_11_R1.LoginListener.b(LoginListener.java:121) [Spigot.jar:git-Spigot-4741400-a1d3777]
	at net.minecraft.server.v1_11_R1.LoginListener.F_(LoginListener.java:57) [Spigot.jar:git-Spigot-4741400-a1d3777]
	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233) [Spigot.jar:git-Spigot-4741400-a1d3777]
	at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140) [Spigot.jar:git-Spigot-4741400-a1d3777]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:842) [Spigot.jar:git-Spigot-4741400-a1d3777]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [Spigot.jar:git-Spigot-4741400-a1d3777]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [Spigot.jar:git-Spigot-4741400-a1d3777]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [Spigot.jar:git-Spigot-4741400-a1d3777]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at net.risenphoenix.ipcheck.database.DatabaseController.addUUID(DatabaseController.java:205) ~[?:?]
	at net.risenphoenix.ipcheck.database.DatabaseController.log(DatabaseController.java:177) ~[?:?]
	at net.risenphoenix.ipcheck.events.PlayerLoginListener.execute(PlayerLoginListener.java:82) ~[?:?]
	at net.risenphoenix.ipcheck.events.PlayerLoginListener.<init>(PlayerLoginListener.java:67) ~[?:?]
	at net.risenphoenix.ipcheck.IPCheck.onPlayerLogin(IPCheck.java:88) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor354.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Spigot.jar:git-Spigot-4741400-a1d3777]
	... 13 more
[17:51:48] [Server thread/INFO]: Disconnecting com.mojang.authlib.GameProfile@2de3099b[id=5ffc199f-ee09-4b62-b1b0-c029a71fd915,name=OpLaMLaM,properties={textures=[com.mojang.authlib.properties.Property@71bde2cc]},legacy=false] (/182.153.229.34:62630): You are not whitelisted on this server!

**Comment by dutchy1001** [comment]
I cant reproduce this error on my test server. 
What version of MC is your server?

Plz next time use [pastebin](http://pastebin.com/) to post error logs

**Comment by mechcalvin** [comment]
1.11.2
If u are a white listed player this error won't occur, u have to try to login as non whitelist player

**Comment by mechcalvin** [comment]
1.11.2 spigot

**Comment by dutchy1001** [comment]
I know how to test. It still wont happen to me.
Have you updated all other plugins/spigot build?

**Comment by dutchy1001** [comment]
Updated to the last build from the spigot buildtools (Build #59 (10-Feb-2017 07:36:06)) and created a new spigot 1.11.2 file. 
It still wont happen to me.
See [here](http://pastebin.com/H7f1X2yf) my startup log including me not whitelisted and deOPed.

**Comment by mechcalvin** [comment]
Are u using MySQL or file as database?

**Comment by dutchy1001** [comment]
I tested both with or without MySQL
Same startup log so no point to post it again.

**Comment by mechcalvin** [comment]
Hmmm, let me try to find out what's the cause of the error by reduce plugins once at a time. Will get back to you

**Comment by dutchy1001** [comment]
There is an issue with the MySQL, after a while it losses connection and gives an error when you try to log in.
Restart the server and see if the same happens.
I'm waiting for an update from our developer to have that fixed.
